baseURL: "https://lptr.github.io/"
languageCode: "en-us"
title: "lptr's blog"
theme: "PaperMod"
googleAnalytics: UA-25254661-1
disqusShortname: lptrs-blog
menu:
  main:
    - name: About
      url: about
      weight: 1
    - name: Archive
      url: archives
      weight: 5
