baseURL: "https://lptr.github.io/"
languageCode: "en-us"
title: "Redneck Overengineering"
theme: "PaperMod"
googleAnalytics: UA-25254661-1
disqusShortname: redneck-overengineering

menu:
  main:
    - name: About
      url: about
      weight: 1
    - name: Archive
      url: archives
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: "Welcome"
    Content: >
      Welcome to my tech blog on the internet.

  socialIcons:
    - name: GitHub
      url: "https://github.com/lptr"
    - name: RSS
      url: "index.xml"
